import { Garment } from '../types/garment';

// Garments now cover all 4 category banners (dresses, outerwear, knitwear, bags)
// plus shoes, so tapping any category shows real matching results.
export const mockGarments: Garment[] = [
    // ---- DRESSES ----
    {
        id: 'g1',
        name: 'Maxi Linen Dress',
        category: 'dresses',
        price: 145,
        thumbnailUrl: 'https://placehold.co/300x375?text=Maxi+Linen+Dress',
        runtimeAssetUrl: 'assets/garments/dresses/maxi_linen_dress.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftShoulder', 'rightShoulder'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: false,
        supportedPoses: ['front'],
    },
    {
        id: 'g2',
        name: 'Silk Evening Dress',
        category: 'dresses',
        price: 210,
        thumbnailUrl: 'https://placehold.co/300x375?text=Silk+Evening+Dress',
        runtimeAssetUrl: 'assets/garments/dresses/silk_evening_dress.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftShoulder', 'rightShoulder'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: false,
        supportedPoses: ['front'],
    },
    {
        id: 'g3',
        name: 'Ribbed Midi Dress',
        category: 'dresses',
        price: 110,
        thumbnailUrl: 'https://placehold.co/300x375?text=Ribbed+Midi+Dress',
        runtimeAssetUrl: 'assets/garments/dresses/ribbed_midi_dress.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftShoulder', 'rightShoulder'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: false,
        supportedPoses: ['front'],
    },
    {
        id: 'g4',
        name: 'Blazer Dress',
        category: 'dresses',
        price: 185,
        thumbnailUrl: 'https://placehold.co/300x375?text=Blazer+Dress',
        runtimeAssetUrl: 'assets/garments/dresses/blazer_dress.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftShoulder', 'rightShoulder'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: false,
        supportedPoses: ['front'],
    },
    // ---- OUTERWEAR ----
    {
        id: 'g5',
        name: 'Wool Overcoat',
        category: 'outerwear',
        price: 290,
        thumbnailUrl: 'https://placehold.co/300x375?text=Wool+Overcoat',
        runtimeAssetUrl: 'assets/garments/outerwear/wool_overcoat.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftShoulder', 'rightShoulder'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: false,
        supportedPoses: ['front'],
    },
    {
        id: 'g6',
        name: 'Classic Denim Jacket',
        category: 'outerwear',
        price: 68,
        thumbnailUrl: 'https://placehold.co/300x375?text=Denim+Jacket',
        runtimeAssetUrl: 'assets/garments/outerwear/denim_jacket.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftShoulder', 'rightShoulder'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: false,
        supportedPoses: ['front'],
    },
    // ---- KNITWEAR ----
    {
        id: 'g7',
        name: 'Cashmere Sweater',
        category: 'knitwear',
        price: 240,
        thumbnailUrl: 'https://placehold.co/300x375?text=Cashmere+Sweater',
        runtimeAssetUrl: 'assets/garments/knitwear/cashmere_sweater.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftShoulder', 'rightShoulder'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: false,
        supportedPoses: ['front'],
    },
    {
        id: 'g8',
        name: 'White Tee',
        category: 'knitwear',
        price: 24,
        thumbnailUrl: 'https://placehold.co/300x375?text=White+Tee',
        runtimeAssetUrl: 'assets/garments/knitwear/white_tee.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftShoulder', 'rightShoulder'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: false,
        supportedPoses: ['front'],
    },
    // ---- BAGS ----
    {
        id: 'g9',
        name: 'Leather Tote Bag',
        category: 'bags',
        price: 165,
        thumbnailUrl: 'https://placehold.co/300x375?text=Leather+Tote',
        runtimeAssetUrl: 'assets/garments/bags/leather_tote.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftHip'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: false,
        supportedPoses: ['front'],
    },
    // ---- SHOES ----
    {
        id: 'g10',
        name: 'Running Sneakers',
        category: 'shoes',
        price: 89,
        thumbnailUrl: 'https://placehold.co/300x375?text=Sneakers',
        runtimeAssetUrl: 'assets/garments/shoes/sneaker.png',
        assetType: '2d_mesh',
        anchorProfile: { primaryLandmarks: ['leftAnkle'], offsetX: 0, offsetY: 0 },
        scale: 1.0,
        mirror: true,
        supportedPoses: ['front'],
    },
];